### ISSUE TITLE
Could not find module 'LeapC.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by TheConceptBoy** [eranegozy/pyleap#1]
```
C:\Users\DevStationPrimary\Downloads\pyleap-master\pyleap-master\example>python test.py
Traceback (most recent call last):
  File "C:\Users\DevStationPrimary\Downloads\pyleap-master\pyleap-master\example\test.py", line 17, in <module>
    from pyleap.leap import getLeapInfo, getLeapFrame
  File "C:\Users\DevStationPrimary\Downloads\pyleap-master\pyleap-master\pyleap\leap.py", line 35, in <module>
    _leap = CDLL(lib_file)
  File "C:\Program Files\Inkscape\lib\python3.9\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'LeapC.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

I have downloaded the libary and the motionleap sdk

I changed to the directory of the example and ran the example python file. 

I also tried to just use the libary by itself via:

```
import sys
import os
os.add_dll_directory('C:/Users/DevStationPrimary/Downloads/pyleap-master/pyleap-master/pyleap/x64')
import leap

print("it works")

result1 = leap.getLeapInfo()
print(result1)

result2 = leap.getLeapFrame()
print(result2 )`
```

and I get:

```
LeapInfo(service=False, connected=False, has_focus=False)
LeapFrame(valid=True, hands=[
  LeapHand(id=-1, palm_pos=[0. 0. 0.], fingers=[
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]])
  LeapHand(id=-1, palm_pos=[0. 0. 0.], fingers=[
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]])])
```

So I suppose this means that I did manage to talk to the library but this implementation is no longer compatible with the latest leap-motion driver? Because the device is definitely plugged in and working as I can see motion leaps control panel display and track my hands.

**Comment by eranegozy** [comment]
What os are you using?
Also, the binaries are not signed / registered, so you have to give permission (in Security prefs) to use them. Did you do that?
